[package]
name = "tiny-cup-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncomm = "0.1.2"
tiny-cup-ref = "0.1.0"
