title = "Tiny-Cup Dimensions (mm)"

[field_dimensions]
width = 1050.0
length = 1500.0
corner_radius = 100.0
center_circle_radius = 150.0

[robot_max_dimensions]
max_length = 150.0
max_width = 150.0
max_height = 300.0

[ball_dimensions]
radius = 30.0
start_position = [0.0, 0.0]

[goal_dimensions]
length = 500.0
height = 300.0
depth = 50.0

[ui_dimensions]
length = 750.0
height = 625.0
button_height = 100.0
multiplier = 0.5